// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJZZEkmWI8lndY-ssMdvsZCiXlZ0JvJc',
    appId: '1:1088441843381:android:f50f0a9dc5fb125474c8fc',
    messagingSenderId: '1088441843381',
    projectId: 'nutriscan-75d57',
    storageBucket: 'nutriscan-75d57.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMAFZBfGe5-4ss07kXD9oH_Jw9wLZJ3Zw',
    appId: '1:1088441843381:ios:90e7043067c9d21b74c8fc',
    messagingSenderId: '1088441843381',
    projectId: 'nutriscan-75d57',
    storageBucket: 'nutriscan-75d57.firebasestorage.app',
    iosBundleId: 'com.vin.nourishshot',
  );
}
