import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:iconly/iconly.dart';
import 'package:nutriscan/config/app_colors.dart';
import 'package:nutriscan/providers/theme/theme_provider.dart';
import 'package:nutriscan/widgets/policy/policy_header.dart';
import 'package:nutriscan/widgets/policy/policy_section.dart';
import 'package:provider/provider.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, child) {
        final isDarkMode = themeProvider.isDarkMode;

        return Scaffold(
          backgroundColor: isDarkMode
              ? AppColors.backgroundDark
              : AppColors.backgroundLight,
          appBar: AppBar(
            title: Text(
              'Terms of Service',
              style: GoogleFonts.poppins(
                fontWeight: FontWeight.bold,
                fontSize: 18,
                color: Colors.white,
              ),
            ),
            backgroundColor: AppColors.primary,
            elevation: 0,
            leading: IconButton(
              icon: const Icon(IconlyLight.arrow_left, color: Colors.white),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
          body: SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Header
                const PolicyHeader(
                  title: 'Terms of Service',
                  subtitle: 'Last updated: April 17, 2026',
                  icon: Icons.description,
                ),
                const SizedBox(height: 24),

                // Content Sections
                const PolicySection(
                  title: 'Acceptance of Terms',
                  content:
                      'By downloading, installing, or using NutriScan, you agree to comply with and be bound by these Terms of Service. If you do not agree, please do not use the application.',
                  icon: Icons.check_circle,
                ),

                const PolicySection(
                  title: 'Medical Disclaimer',
                  content:
                      'NutriScan is an AI-powered tool for nutritional estimation. THE RESULTS PROVIDED (CALORIES, MACRONUTRIENTS, ETC.) ARE ESTIMATIONS ONLY. This app is not a medical device and its content should not be interpreted as medical advice. Always consult a healthcare professional before making significant changes to your diet.',
                  icon: Icons.health_and_safety,
                ),

                const PolicySection(
                  title: 'Subscriptions and Payments',
                  content:
                      'Premium features are available through auto-renewing subscriptions via Google Play or Apple App Store. Subscriptions will be charged to your account at confirmation of purchase and will automatically renew unless cancelled at least 24 hours before the end of the current period.',
                  icon: Icons.verified_user,
                ),

                const PolicySection(
                  title: 'AI Content',
                  content:
                      'The nutrition analysis is generated by AI models (Groq). While we strive for accuracy, the AI may occasionally produce incorrect information. We are not liable for any decisions made based on AI-generated nutrition estimates.',
                  icon: Icons.auto_awesome,
                ),

                const PolicySection(
                  title: 'User Conduct',
                  content:
                      'You agree to use NutriScan only for lawful purposes. You are responsible for the images and data you upload and must ensure you have the right to share them.',
                  icon: Icons.person_pin,
                ),

                const PolicySection(
                  title: 'Limitations of Liability',
                  content:
                      'To the maximum extent permitted by law, NutriScan and its developers shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the service.',
                  icon: Icons.block,
                ),

                const PolicySection(
                  title: 'Modifications',
                  content:
                      'We reserve the right to modify these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.',
                  icon: Icons.edit,
                ),

                const SizedBox(height: 32),
              ],
            ),
          ),
        );
      },
    );
  }
}
